### ISSUE TITLE
ETRI가 죽었슴돠;;

### ISSUE THREAD

**Issue by pvvng** [pvvng/youtube-comment#4]
```bash
Axios error: <html><head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

Error: API 요청 실패: Gateway Time-out
    at callMorpAPI (webpack-internal:///(api)/./@util/functions/wordAPI/callMorpAPI.ts:27:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAnalyzedWordData (webpack-internal:///(api)/./@util/functions/wordAPI/getAnalyzedWordData.ts:56:25)
    at async handler (webpack-internal:///(api)/./pages/api/post/word.ts:67:44)
    at async K (C:\Users\user\Desktop\youtube2\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:2871)
    at async U.render (C:\Users\user\Desktop\youtube2\node_modules\next\dist\compiled\next-server\pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\next-server.js:598:9)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\next-server.js:269:37)
    at async DevServer.handleRequestImpl (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\devr\Desktop\youtube2\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\user\Desktop\youtube2\node_modules\next\dist\server\lib\router-server.js:374:13)
```
저한테 왜이러세요

**Comment by pvvng** [comment]
youtube나 Clova 같은 API는 정상작동해요. 저한테 왜이러세요

**Comment by pvvng** [comment]
그리고 Clova API가 11월까지만 운영한다고 합니다 억까 레전드

**Comment by pvvng** [comment]
걍 flask 서버 만들고 있음여 수고바이
![image](https://github.com/user-attachments/assets/db37b845-1d50-47e3-b2f6-f395d12af627)
